server:
  port: 8881
  servlet:    session:      timeout: 1800 
spring:
  application:
    name: resource-server
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booyaka?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true
    username: root  
    password: root
    hikari:      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-test-query: SELECT 1  thymeleaf:    cache: false
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
security:  oauth2:    resource:      user-info-uri: BUGFIX    client:      client-id: client_a
      client-secret: secret
      authorized-grant-types:      - client_credentials
      - password
      - authorization_code
      - implicit
      - refresh_token
      access-token-uri: 127.0.0.1:8888/oauth/token
      
 
logging:  level:    '[com.booyaka]': debug