server:
  port: 9999spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth2
          uri: lb://oauth2-server
          predicates:
            - Method=GET,POST
        - id: resource
          uri: lb://resource-server
          predicates:
            - Method=GET,POST
    nacos:      server-addr: 127.0.0.1:8848
